### PR TITLE
closes #450

### LINKED ISSUE #450: Investigate on changing map projection to EPSG:32632 (UTM32)
Evaluate the working and not working features and a plan for migration

### PR DESCRIPTION
**Pull request by kappu72**

### CODE REVIEW

File: frontend/js/actions/addmap.js [hunk 1]
```diff
@@ -91,7 +91,7 @@ function addSiraLayersIncart(layers) {
 function addLayers(layers, useTitle, useGroup) {
     return (dispatch, getState) => {
         const node = ((getState()).addmap || {}).node;
-        const layersConfig = layers.slice().reverse().map((layer) => AddMapUtils.getLayerConfing(layer, 'EPSG:3857', useTitle, useGroup, {}, node));
+        const layersConfig = layers.slice().reverse().map((layer) => AddMapUtils.getLayerConfing(layer, 'EPSG:32632', useTitle, useGroup, {}, node));
```
Comment (mbarto) [inline frontend/js/actions/addmap.js]: Can we make the CRS an action parameter?

File: frontend/js/utils/UTM32NUtils.js [hunk 2]
```diff
@@ -0,0 +1,19 @@
+/**
```
Comment (mbarto) [inline frontend/js/utils/UTM32NUtils.js]: Let's call this ProjUtils, so that we can add more in the future (if needed)
